<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC6htrz7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC6htrz7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerC6htrz7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerC6htrz7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerC6htrz7\appProdProjectContainer([
    'container.build_hash' => 'C6htrz7',
    'container.build_id' => '090ceb43',
    'container.build_time' => 1627366197,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC6htrz7');
