<?php

namespace AppBundle\Repository;

/**
 * homeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class homeRepository extends \Doctrine\ORM\EntityRepository
{
}
