<?php

namespace AppBundle\Repository;

/**
 * imgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imgRepository extends \Doctrine\ORM\EntityRepository
{
}
